services:
  node:
    build: .
    ports:
      - "3000:3000"
  mongo:
    image: "mongo"
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: "mongo-express"
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
volumes:
  mongo-data:
    driver: local
